title: AxieDex - The Ultimate Axie Infinity Extension
logo: /assets/img/logo.png
description: AxieDex enhances the display of Axies information in the Axie Marketplace. This extension is a must-have for any players and breeders of Axie Infinity 🎮
theme: jekyll-theme-minimal
